import { resolve } from 'path'

const pages = [
  {name: 'index', path: resolve(__dirname, '../index.html')},
  {name: 'home', path: resolve(__dirname, '../pages/home.html')},
  {name: '404', path: resolve(__dirname, '../pages/404.html')},
  {name: 'blog', path: resolve(__dirname, '../pages/blog.html')},
  {name: 'workspace', path: resolve(__dirname, '../pages/workspace.html')},
  {name: 'about', path: resolve(__dirname, '../pages/about.html')},
  {name: 'professors', path: resolve(__dirname, '../pages/professors.html')},
  {name: 'catalog', path: resolve(__dirname, '../pages/catalog.html')},
  {name: 'home', path: resolve(__dirname, '../pages/home.html')},
  {name: 'course', path: resolve(__dirname, '../pages/course.html')},
  {name: 'calendar', path: resolve(__dirname, '../pages/calendar.html')},

  {name: 'style', path: resolve(__dirname, '../src/scss/style.scss')},
  {name: 'header', path: resolve(__dirname, '../src/scss/components/header.scss')},
  {name: 'footer', path: resolve(__dirname, '../src/scss/components/footer.scss')},
  {name: 'scroll-parallax', path: resolve(__dirname, '../src/scss/components/scroll-parallax.scss')},
  {name: '404-css', path: resolve(__dirname, '../src/scss/components/404.scss')},
  {name: 'navhero', path: resolve(__dirname, '../src/scss/components/navhero.scss')},
  {name: 'blog-css', path: resolve(__dirname, '../src/scss/components/blog.scss')},
  {name: 'workspace-css', path: resolve(__dirname, '../src/scss/components/workspace.scss')},
  {name: 'prefooter-css', path: resolve(__dirname, '../src/scss/components/prefooter.scss')},
  {name: 'fullhero-css', path: resolve(__dirname, '../src/scss/components/fullhero.scss')},
  {name: 'tech-cards-css', path: resolve(__dirname, '../src/scss/components/tech-cards.scss')},
  {name: 'history-css', path: resolve(__dirname, '../src/scss/components/history.scss')},
  {name: 'brands-css', path: resolve(__dirname, '../src/scss/components/brands.scss')},
  {name: 'recognize-css', path: resolve(__dirname, '../src/scss/components/recognize.scss')},
  {name: 'masters-reviews-css', path: resolve(__dirname, '../src/scss/components/masters-reviews.scss')},
  {name: 'professors-css', path: resolve(__dirname, '../src/scss/components/professors.scss')},
  {name: 'courses-css', path: resolve(__dirname, '../src/scss/components/courses.scss')},
  {name: 'hero-css', path: resolve(__dirname, '../src/scss/components/hero.scss')},
  {name: 'cards-css', path: resolve(__dirname, '../src/scss/components/cards.scss')},
  {name: 'path-css', path: resolve(__dirname, '../src/scss/components/path.scss')},
  {name: 'talent-css', path: resolve(__dirname, '../src/scss/components/talent.scss')},
  {name: 'counters-css', path: resolve(__dirname, '../src/scss/components/counters.scss')},
  {name: 'results-css', path: resolve(__dirname, '../src/scss/components/results.scss')},
  {name: 'students-css', path: resolve(__dirname, '../src/scss/components/students.scss')},
  {name: 'experts-css', path: resolve(__dirname, '../src/scss/components/experts.scss')},
  {name: 'home-professors-css', path: resolve(__dirname, '../src/scss/components/home-professors.scss')},
  {name: 'home-figure-css', path: resolve(__dirname, '../src/scss/components/home-figure.scss')},
  {name: 'formats-css', path: resolve(__dirname, '../src/scss/components/formats.scss')},
  {name: 'approach-css', path: resolve(__dirname, '../src/scss/components/approach.scss')},
  {name: 'partners-css', path: resolve(__dirname, '../src/scss/components/partners.scss')},
  {name: 'faq-css', path: resolve(__dirname, '../src/scss/components/faq.scss')},
  {name: 'course-css', path: resolve(__dirname, '../src/scss/components/course.scss')},
  {name: 'iconrows-css', path: resolve(__dirname, '../src/scss/components/iconrows.scss')},
  {name: 'course-pay-css', path: resolve(__dirname, '../src/scss/components/course-pay.scss')},
  {name: 'calendar-css', path: resolve(__dirname, '../src/scss/components/calendar.scss')},

  {name: 'header-js', path: resolve(__dirname, '../src/js/components/header.js')},
  {name: 'footer-js', path: resolve(__dirname, '../src/js/components/footer.js')},
  {name: 'footer-js', path: resolve(__dirname, '../src/js/components/footer.js')},
  {name: 'scroll-parallax-js', path: resolve(__dirname, '../src/js/components/scroll-parallax.js')},
  {name: 'workspace-js', path: resolve(__dirname, '../src/js/components/workspace.js')},
  {name: 'history-js', path: resolve(__dirname, '../src/js/components/history.js')},
  {name: 'brands-js', path: resolve(__dirname, '../src/js/components/brands.js')},
  {name: 'masters-reviews-js', path: resolve(__dirname, '../src/js/components/masters-reviews.js')},
  {name: 'professors-js', path: resolve(__dirname, '../src/js/components/professors.js')},
  {name: 'courses-js', path: resolve(__dirname, '../src/js/components/courses.js')},
  {name: 'home-js', path: resolve(__dirname, '../src/js/components/home.js')},
  {name: 'course-js', path: resolve(__dirname, '../src/js/components/course.js')},
  {name: 'calendar-js', path: resolve(__dirname, '../src/js/components/calendar.js')},
];

export default pages